import type { NextPage } from "next";
import Head from "next/head";
import CodeMirrorWrapper from "../components/CodeMirrorWrapper"
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>WeScheme 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen relative">
        <Header></Header>
        <CodeMirrorWrapper></CodeMirrorWrapper>
      </main>
    </>
  );
};

export default Home;
