import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  // const code = 'const a = 0;';

  return (
    <>
      <Head>
        <title>WeScheme 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full flex">
        <div className="h-1 w-full bg-black text-red-500">
          go to /openEditor
        </div>
      </main>
    </>
  );
};

export default Home;
